name: Process Google Sheets

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  process_sheets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install jq

    - name: cleanup files
      run: |
        rm sheets_data.json processed_sheets.json

    - name: Fetch Google Sheets data
      run: |
        curl 'https://sheets.googleapis.com/v4/spreadsheets/1odptlMt5nRGqyfviszx2zGXZHBm2I1WoXtks0e51ESU/values/Diplomacy!A1%3ABT?key=${{ secrets.GOOGLE_SHEETS_API_KEY }}' \
          --header 'Authorization: Bearer ' \
          --header 'Accept: application/json' \
          --compressed > sheets_data.json

    - name: Process Sheets data
      run: |
        processed_data=$(jq -r '.values[1:] | map({Nations: .[0], "Nation Check": .[1], "Overlord": .[2], "Eco Vassals": .[3], "Eco Over.": .[4], "Compare": .[5], "MP Vassals": .[6], "MP Over.": .[7], "Compare": .[8], "20% Total": .[9], "Vassal Type": .[10], "": .[11], "L. Desire": .[12], "Base": .[13], "Comparison": .[14], "Individual": .[15], "Friend/Rival": .[16], "Taxes": .[17], "": .[18], "Indep War?": .[19], "Autonomy": .[20], "Threshold": .[21], "Chaotic?": .[22], "Deceptive?": .[23], "Honor?": .[24], "Indep.?": .[25], "Unity?": .[26], "Ov. Culture": .[27], "Ov. Religion": .[28], "Non-aggression Pacts": .[29], "Defensive Pacts": .[30], "": .[31], "Military Alliances": .[32], "": .[33], "Limit": .[34], "Trade 1": { "Value": .[35], "Trade 1 Value": .[36] }, "Trade 2": { "Value": .[37], "Trade 2 Value": .[38] }, "Trade 3": { "Value": .[39], "Trade 3 Value": .[40] }, "Trade 4": { "Value": .[41], "Trade 4 Value": .[42] }, "Trade 5": { "Value": .[43], "Trade 5 Value": .[44] }, "Trade 6": { "Value": .[45], "Trade 6 Value": .[46] }, "Trade 7": { "Value": .[47], "Trade 7 Value": .[48] }, "Trade 8": { "Value": .[49], "Trade 8 Value": .[50] }, "Trade 9": { "Value": .[51], "Trade 9 Value": .[52] }, "Trade 10": { "Value": .[53], "Trade 10 Value": .[54] }, "Trade 11": { "Value": .[55], "Trade 11 Value": .[56] }, "Trade 12": { "Value": .[57], "Trade 12 Value": .[58] }, "Trade 13": { "Value": .[59], "Trade 13 Value": .[60] }, "Trade 14": { "Value": .[61], "Trade 14 Value": .[62] }, "Trade 15": { "Value": .[63], "Trade 15 Value": .[64] }, "Raw Trade Income": .[65], "Tariffs": .[66], "Trade Income": .[67], "NAPs": .[68], "Def. Pacts": .[69], "Mil. Pacts": .[70], "Trades": .[71]})' sheets_data.json)
        echo "$processed_data" > processed_sheets.json

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add processed_sheets.json
        git commit -m "Update processed Sheets data [skip ci]"
        git push
