name: Process Google Sheets

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  process_sheets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install jq

    - name: cleanup files
      run: |
        rm -f sheets_data.json processed_sheets.json

    - name: Fetch Google Sheets data
      run: |
        curl 'https://sheets.googleapis.com/v4/spreadsheets/1odptlMt5nRGqyfviszx2zGXZHBm2I1WoXtks0e51ESU/values/Diplomacy!A1%3ABT?key=${{ secrets.GOOGLE_SHEETS_API_KEY }}' \
          --header 'Authorization: Bearer ' \
          --header 'Accept: application/json' \
          --compressed > diplo_data.json
        curl 'https://sheets.googleapis.com/v4/spreadsheets/1odptlMt5nRGqyfviszx2zGXZHBm2I1WoXtks0e51ESU/values/Armies!A1%3AOBX?key=${{ secrets.GOOGLE_SHEETS_API_KEY }}' \
          --header 'Authorization: Bearer ' \
          --header 'Accept: application/json' \
          --compressed > army_data.json
        curl 'https://sheets.googleapis.com/v4/spreadsheets/1odptlMt5nRGqyfviszx2zGXZHBm2I1WoXtks0e51ESU/values/Technology!A1%3AOL?key=${{ secrets.GOOGLE_SHEETS_API_KEY }}' \
          --header 'Authorization: Bearer ' \
          --header 'Accept: application/json' \
          --compressed > tech_data.json
        curl 'https://sheets.googleapis.com/v4/spreadsheets/1odptlMt5nRGqyfviszx2zGXZHBm2I1WoXtks0e51ESU/values/Research!A2%3AODD?key=${{ secrets.GOOGLE_SHEETS_API_KEY }}' \
          --header 'Authorization: Bearer ' \
          --header 'Accept: application/json' \
          --compressed > research_data.json


    - name: Process Sheets data
      run: |
        army_data=$(jq -r '.values[1:] | map(select(.[0] != null) | { (.[0]):{Nations: .[0], "Nation Check": .[1], "Pow_Army": .[13], "Pow_Navy": .[14], "Manpower": .[26], "Manpower Avail.": .[36], "Upkeep": .[41], "Upkeep Army": .[42], "Upkeep Navy": .[43] , "Upkeep Mercenary": .[44], "Faction Troops": .[46], "Mob": .[47], "Auxilla Infantry": .[48], "Auxilla Archers": .[49], "Auxilla Cavalry": .[50], "Bronze Warriors": .[51], "Bronze Cavalry": .[52], "Hoplites": .[53], "Battering Ram": .[54], "Stone Thrower": .[54], "Classical Warriors": .[56],  "Classical Archers": .[57],  "Classical Cavalry": .[56],  "Legionnaire": .[57],  "Cataphracts": .[58],  "Siege Towers": .[59],  "Ballista": .[60],  "Penteconter": .[61],  "Ancient Transport": .[62],  "Quadrireme": .[63],  "Missile Trireme": .[64],  "Raiding Hemiolia": .[65],  "Fire Ship": .[66],  "Artillery Quinquereme": .[67],  "Classical Transport": .[68],  "Slots": .[69],  "Merc 1": .[70],  "Merc 2": .[71],  "Merc 3": .[72],  "Merc 4": .[73]}}) | add' army_data.json)
        echo "$army_data" > army.json

        diplo_data=$(jq -r '.values[1:] | map(select(.[0] != null) | { (.[0]):{Nations: .[0], "Nation Check": .[1], "Overlord": .[2], "Eco Vassals": .[3], "Eco Over.": .[4], "Compare": .[5], "MP Vassals": .[6], "MP Over.": .[7], "Compare": .[8], "20% Total": .[9], "Vassal Type": .[10], "": .[11], "L. Desire": .[12], "Base": .[13], "Comparison": .[14], "Individual": .[15], "Friend/Rival": .[16], "Taxes": .[17], "": .[18], "Indep War?": .[19], "Autonomy": .[20], "Threshold": .[21], "Chaotic?": .[22], "Deceptive?": .[23], "Honor?": .[24], "Indep.?": .[25], "Unity?": .[26], "Ov. Culture": .[27], "Ov. Religion": .[28], "Non-aggression Pacts": .[29], "Defensive Pacts": .[30], "Defensive Pacts 2": .[31], "Military Alliances": .[32], "Military Alliances 2": .[33], "Limit": .[34], "Trade 1": { "Value": .[35], "Trade 1 Value": .[36] }, "Trade 2": { "Value": .[37], "Trade 2 Value": .[38] }, "Trade 3": { "Value": .[39], "Trade 3 Value": .[40] }, "Trade 4": { "Value": .[41], "Trade 4 Value": .[42] }, "Trade 5": { "Value": .[43], "Trade 5 Value": .[44] }, "Trade 6": { "Value": .[45], "Trade 6 Value": .[46] }, "Trade 7": { "Value": .[47], "Trade 7 Value": .[48] }, "Trade 8": { "Value": .[49], "Trade 8 Value": .[50] }, "Trade 9": { "Value": .[51], "Trade 9 Value": .[52] }, "Trade 10": { "Value": .[53], "Trade 10 Value": .[54] }, "Trade 11": { "Value": .[55], "Trade 11 Value": .[56] }, "Trade 12": { "Value": .[57], "Trade 12 Value": .[58] }, "Trade 13": { "Value": .[59], "Trade 13 Value": .[60] }, "Trade 14": { "Value": .[61], "Trade 14 Value": .[62] }, "Trade 15": { "Value": .[63], "Trade 15 Value": .[64] }, "Raw Trade Income": .[65], "Tariffs": .[66], "Trade Income": .[67], "NAPs": .[68], "Def. Pacts": .[69], "Mil. Pacts": .[70], "Trades": .[71]}}) | add' diplo_data.json)
        echo "$diplo_data" > diplo.json

        tech_data=$(jq -r '.values[1:] | map(select(.[0] != null) | { (.[0]):{Technology: .[0], "Age": .[1], "Type": .[2], "Difficulty": .[6], "Req 1": .[7], "Req 2": .[8], "Req 3": .[9], "Req 4": .[10]}}) | add' tech_data.json)
        echo "$tech_data" > tech.json

        research_data=$(jq -r '.values[1:] | map(select(.[0] != null) | { (.[0]):{Nations: .[0], "Nation Check": .[1], "Tribal Governance": .[32], "Tribal Culture": .[33], "Tribal Religion": .[34], "Writing": .[35], "Tribal Agriculture": .[36], "Animal Husbandry": .[37], "Basic Storage": .[38], "Archery": .[39], "Military Training": .[40], "Riders": .[41], "Military Camp": .[42], "Tribal Infrastructure": .[43], "Tribal Commerce": .[44], "Basic Construction": .[45], "Cartography": .[46], "Copper Working": .[47], "Metal Forges": .[48], "Bronze Working": .[49], "Code of Laws": .[50], "Organized Faith": .[51], "Traditions": .[52], "Plowshares": .[53], "Windmills": .[54], "Basic Ship Design": .[55], "Barding": .[56], "Bronze Armor": .[57], "Military Instructors": .[58], "Merchant Guilds": .[59], "Cargo Holds": .[60], "Masonry": .[61], "Advanced Construction": .[62], "Bronze Toolmaking": .[63], "Siegecraft": .[64], "Mineshafts": .[65], "Iron Working": .[66], "Classical Governance": .[67], "National Defense": .[68], "Myths and Fables": .[69], "Paper and Ink Records": .[70], "Irrigation": .[71], "Weighted Nets": .[72], "Two-Crop Rotation": .[73], "Advanced Tactics": .[74], "Iron Armor": .[75], "Stirrups": .[76], "War Horses": .[77], "Officer Academy": .[78], "Supply Wagons": .[79], "Advanced Ship Design": .[80], "Specialized Ship Design": .[81], "Classical Construction": .[82], "Interior Wells": .[83], "Watchtowers": .[84], "Gatehouses": .[85], "Banking Guilds": .[86], "Iron Toolmaking": .[87], "Bellows": .[88], "Advanced Siegecraft": .[89], "Mining Camps": .[90], "Arena Games": .[91], "Guilds": .[92], "Bread and Circuses": .[93], "Greens and Blues": .[94], "One Small Step": .[95], "Estate Farming": .[96], "Fishing Fleets": .[97], "Classical Planning": .[98], "City Planning": .[99], "Artisan Guilds": .[100], "Stonemason Guilds": .[101], "Classical Storage": .[102], "Standardized Coinage": .[103], "Classic Siegecraft": .[104], "Mining Guilds": .[105], "Water Mining": .[106]}}) | add' research_data.json)
         echo "$research_data" > research.json

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add diplo.json
        git add army.json
        git add tech.json
        git add research.json
          git commit -m "Update processed Sheets data [skip ci]"
          git push
